---
- name: Install and Configure Apache with krNetworkCloud Page
  hosts: all
  become: yes

  tasks:

    - name: Install Apache HTTPD
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Ensure Apache is running and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Ensure /var/www/html directory exists
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        mode: '0755'
        owner: root
        group: root



- name: Create index.html with krNetworkCloud info and link
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache

# Handler to restart Apache
handlers:
  - name: Restart Apache
    ansible.builtin.service:
      name: apache2    # use 'httpd' on CentOS/RHEL
      state: restarted


  #   - name: Create index.html with krNetworkCloud info and link
  #     ansible.builtin.copy:
  #       src: index.html
  #       dest: /var/www/html/index.html
  #       owner: root
  #       group: root
  #       mode: '0644'
  #     notify: Restart Apache

  # handlers:
  #   - name: Restart Apache
  #     ansible.builtin.service:
  #       name: httpd
  #       state: restarted


